import { View, StyleSheet, Alert, Text, TouchableOpacity, Image } from "react-native";
export const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: "#f8f9fa",
    },
    container: {
      flex: 1,
      backgroundColor: "#f8f9fa",
    },
    scrollContainer: {
      padding: 16,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: "#f8f9fa",
    },
    loadingText: {
      marginTop: 12,
      fontSize: 16,
      color: '#666',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 16,
      backgroundColor: 'white',
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
    },
    backButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: '#f8f9fa',
    },
    refreshIconButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: '#EFF6FF',
    },
    truckOverviewCard: {
      backgroundColor: 'white',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
      overflow: 'hidden',
      marginBottom: 16,
      flexDirection: 'row',
      padding: 16,
    },
    truckImageContainer: {
      marginRight: 16,
      justifyContent: 'center',
    },
    truckIconContainer: {
      width: 80,
      height: 80,
      borderRadius: 8,
      backgroundColor: '#EFF6FF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    truckInfoContainer: {
      flex: 1,
      justifyContent: 'center',
    },
    truckModel: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#333',
    },
    truckNumber: {
      fontSize: 16,
      color: '#666',
      marginTop: 4,
    },
    truckIdContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
    },
    truckIdText: {
      fontSize: 14,
      color: '#666',
      marginLeft: 4,
    },
    detailCard: {
      backgroundColor: 'white',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
      overflow: 'hidden',
      marginBottom: 16,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#333',
      marginLeft: 8,
    },
    cardContent: {
      padding: 16,
    },
    revisionDetails: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    dateCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: '#EFF6FF',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    dateDay: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#6366F1',
    },
    dateMonth: {
      fontSize: 14,
      color: '#6366F1',
    },
    revisionInfo: {
      flex: 1,
    },
    revisionDate: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#333',
    },
    revisionType: {
      fontSize: 14,
      color: '#666',
      marginTop: 2,
    },
    revisionMileage: {
      fontSize: 14,
      color: '#666',
      marginTop: 2,
    },
    divider: {
      height: 1,
      backgroundColor: '#f0f0f0',
      marginVertical: 16,
    },
    nextRevisionContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    nextRevisionLabel: {
      fontSize: 14,
      color: '#666',
    },
    nextRevisionDate: {
      fontSize: 15,
      fontWeight: '500',
      color: '#333',
    },
    expirationItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    expirationDetails: {
      flex: 1,
    },
    expirationTitle: {
      fontSize: 15,
      fontWeight: '500',
      color: '#333',
    },
    expirationDate: {
      fontSize: 14,
      color: '#666',
      marginTop: 2,
    },
    expirationStatus: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      marginLeft: 8,
    },
    expirationStatusText: {
      fontSize: 12,
      fontWeight: '600',
    },
    specificationsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    specificationItem: {
      width: '48%',
      marginBottom: 16,
    },
    specificationLabel: {
      fontSize: 14,
      color: '#666',
      marginBottom: 4,
    },
    specificationValue: {
      fontSize: 15,
      fontWeight: '500',
      color: '#333',
    },
    maintenanceItem: {
      flexDirection: 'row',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    maintenanceDate: {
      width: 90,
      marginRight: 12,
    },
    maintenanceDateText: {
      fontSize: 14,
      color: '#6366F1',
      fontWeight: '500',
    },
    maintenanceDetails: {
      flex: 1,
    },
    maintenanceType: {
      fontSize: 15,
      fontWeight: '500',
      color: '#333',
    },
    maintenanceDescription: {
      fontSize: 14,
      color: '#666',
      marginTop: 2,
    },
    maintenanceMileage: {
      fontSize: 13,
      color: '#666',
      marginTop: 4,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    emptyIconContainer: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: '#EFF6FF',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 8,
    },
    emptyText: {
      fontSize: 16,
      color: '#666',
      marginBottom: 24,
      textAlign: 'center',
    },
    refreshButton: {
      flexDirection: 'row',
      backgroundColor: '#6366F1',
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    refreshButtonText: {
      color: 'white',
      fontWeight: 'bold',
      fontSize: 16,
    },
  });