import { StyleSheet } from "react-native";
import COLORS from "../../utils/COLORS.js";
// Enhanced color palette for production consistency
const ENHANCED_COLORS = {
  ...COLORS,
  background: "#F4F5FB",
  card: "#FFFFFF",
  primary: "#5A5BDE",
  secondary: "#6F89FF",
  accent: "#FF8C66",
  accent2: "#81C3F8",
  dark: "#373A56",
  medium: "#6B6F8D",
  light: "#A0A4C1",
  border: "#E2E5F1",
  success: "#63C6AE",
  warning: "#FFBD59",
  danger: "#FF7285",
};
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ENHANCED_COLORS.background,
  },
  scrollViewContent: {
    paddingBottom: 32,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 8,
  },
  backButton: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: ENHANCED_COLORS.card,
    shadowColor: ENHANCED_COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  // Profile Section - More prominent and friendly
  profileInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
    marginHorizontal: 16,
    marginTop: 8,
    backgroundColor: ENHANCED_COLORS.card,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  profileContainer: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: ENHANCED_COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: ENHANCED_COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  profileInitials: {
    fontSize: 24,
    fontWeight: '700',
    color: ENHANCED_COLORS.card,
  },
  profileTextContainer: {
    flex: 1,
    marginLeft: 16,
  },
  profileName: {
    fontSize: 22,
    fontWeight: '600',
    color: ENHANCED_COLORS.dark,
    marginBottom: 4,
  },
  profileRole: {
    fontSize: 16,
    color: ENHANCED_COLORS.primary,
    fontWeight: '500',
    marginBottom: 2,
  },
  profileCompany: {
    fontSize: 14,
    color: ENHANCED_COLORS.medium,
    fontWeight: '400',
  },
  // Data Container - Cleaner layout
  dataContainer: {
    backgroundColor: ENHANCED_COLORS.card,
    marginHorizontal: 16,
    marginTop: 20,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  dataTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: ENHANCED_COLORS.dark,
    marginBottom: 20,
  },
  dataRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  dataLabel: {
    fontSize: 15,
    color: ENHANCED_COLORS.medium,
    fontWeight: '500',
    minWidth: 120,
  },
  dataDivider: {
    fontSize: 14,
    color: COLORS.light,
    marginHorizontal: 12,
  },
  dataValue: {
    fontSize: 15,
    color: ENHANCED_COLORS.dark,
    fontWeight: '500',
    flex: 1,
  },
  // Alert Container for expiring documents
  alertContainer: {
    backgroundColor: ENHANCED_COLORS.card,
    marginHorizontal: 16,
    marginTop: 16,
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.warning,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  alertHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  alertTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: ENHANCED_COLORS.dark,
    marginLeft: 8,
  },
  alertItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  alertDocTitle: {
    fontSize: 14,
    color: ENHANCED_COLORS.dark,
    fontWeight: '500',
    flex: 1,
  },
  alertExpiration: {
    fontSize: 13,
    fontWeight: '600',
  },
  // Settings Section - More organized
  settingsTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: ENHANCED_COLORS.dark,
    marginTop: 32,
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  settingOuterContainer: {
    marginVertical: 6,
    marginHorizontal: 16,
    backgroundColor: ENHANCED_COLORS.card,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  settingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  settingIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingTextContainer: {
    flex: 1,
    marginLeft: 16,
  },
  settingTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: ENHANCED_COLORS.dark,
    marginBottom: 2,
  },
  settingSubtitle: {
    fontSize: 14,
    color: ENHANCED_COLORS.medium,
    lineHeight: 18,
  },
  badgeContainer: {
    backgroundColor: ENHANCED_COLORS.primary,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 8,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: ENHANCED_COLORS.card,
  },
  // Dropdown containers
  dropdownContainer: {
    padding: 20,
    backgroundColor: COLORS.background,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  dropdownText: {
    fontSize: 15,
    color: ENHANCED_COLORS.medium,
    marginBottom: 16,
    textAlign: 'center',
  },
  noDocumentsText: {
    fontSize: 14,
    color: COLORS.light,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  // Document items
  documentItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: ENHANCED_COLORS.card,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  documentInfo: {
    flex: 1,
  },
  documentTitle: {
    fontSize: 15,
    fontWeight: '500',
    color: ENHANCED_COLORS.dark,
    marginBottom: 2,
  },
  documentExpiration: {
    fontSize: 13,
    color: ENHANCED_COLORS.medium,
  },
  // Call button
  callButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: ENHANCED_COLORS.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    shadowColor: ENHANCED_COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  callButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: ENHANCED_COLORS.card,
    marginLeft: 10,
  },
  // Sign Out Button - More prominent but safe styling
  signOutButton: {
    marginTop: 32,
    marginHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: ENHANCED_COLORS.card,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.danger,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  signOutText: {
    fontSize: 17,
    color: COLORS.danger,
    fontWeight: '600',
  },
  // Legacy styles that might be needed elsewhere
  profileImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  notificationButton: {
    padding: 8,
  },
  sectionContainer: {
    marginTop: 20,
    paddingHorizontal: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTitleContainer: {
    flex: 1,
    marginLeft: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '500',
  },
  sectionSubtitle: {
    fontSize: 14,
    color: ENHANCED_COLORS.medium,
    marginTop: 2,
  },
  addIconCircle: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: ENHANCED_COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    bottom: -2,
    right: -2,
  },
});