import { View, StyleSheet, Alert, Text, TouchableOpacity, Image } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    backButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: '#f8f9fa',
    },
    settingOuterContainer: {
      marginVertical: 8,
      marginHorizontal: 16,
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    profileInfoContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    profileImage: {
      width: 70,
      height: 70,
      borderRadius: 35,
    },
    profileTextContainer: {
      flex: 1,
      marginLeft: 12,
    },
    profileName: {
      fontSize: 20,
      fontWeight: '500',
    },
    profileRole: {
      fontSize: 16,
      color: '#4285F4',
      marginTop: 2,
    },
    notificationButton: {
      padding: 8,
    },
    sectionContainer: {
      marginTop: 20,
      paddingHorizontal: 16,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
    },
    iconCircle: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#f5f5f5',
      justifyContent: 'center',
      alignItems: 'center',
    },
    sectionTitleContainer: {
      flex: 1,
      marginLeft: 12,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '500',
    },
    sectionSubtitle: {
      fontSize: 14,
      color: '#777',
      marginTop: 2,
    },
    dataContainer: {
      backgroundColor: '#f9f9f9',
      marginHorizontal: 16,
      marginTop: 12,
      padding: 16,
      borderRadius: 12,
    },
    dataTitle: {
      fontSize: 18,
      fontWeight: '500',
      marginBottom: 12,
    },
    dataRow: {
      flexDirection: 'row',
      marginVertical: 6,
    },
    dataLabel: {
      fontSize: 14,
      color: '#777',
    },
    dataDivider: {
      fontSize: 14,
      color: '#777',
      marginHorizontal: 6,
    },
    dataValue: {
      fontSize: 14,
      color: '#777',
    },
    settingsTitle: {
      fontSize: 22,
      fontWeight: '500',
      marginTop: 24,
      marginBottom: 12,
      paddingHorizontal: 16,
    },
    settingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    settingIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#f5f5f5',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
    },
    addIconCircle: {
      position: 'absolute',
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: '#4285F4',
      justifyContent: 'center',
      alignItems: 'center',
      bottom: -2,
      right: -2,
    },
    settingTextContainer: {
      flex: 1,
      marginLeft: 12,
    },
    settingTitle: {
      fontSize: 16,
      fontWeight: '500',
    },
    settingSubtitle: {
      fontSize: 14,
      color: '#777',
      marginTop: 2,
    },
    signOutButton: {
      marginTop: 24,
      marginHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 8,
      backgroundColor: '#f5f5f5',
      alignItems: 'center',
    },
    signOutText: {
      fontSize: 16,
      color: '#F44336',
      fontWeight: '500',
    },
    profileContainer: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: "#6366F1",
      justifyContent: "center",
      alignItems: "center",
    },
    dropdownContainer: {
      padding: 16,
      backgroundColor: '#F8FAFC',
      borderTopWidth: 1,
      borderTopColor: '#E2E8F0',
    },
    dropdownText: {
      fontSize: 14,
      color: '#64748B',
      marginBottom: 12,
    },
    callButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#6366F1',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 8,
    },
    callButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#FFFFFF',
      marginLeft: 8,
    },
  });