import { StyleSheet, Dimensions } from 'react-native';
// Color palette
const COLORS = {
  background: "#F4F5FB",
  card: "#FFFFFF",
  primary: "#5A5BDE",
  secondary: "#6F89FF",
  accent: "#FF8C66",
  accent2: "#81C3F8",
  dark: "#373A56",
  medium: "#6B6F8D",
  light: "#A0A4C1",
  border: "#E2E5F1",
  success: "#63C6AE",
  warning: "#FFBD59",
  danger: "#FF7285",
  selected: "#E8F5E8",
};
const { width: screenWidth } = Dimensions.get('window');
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: COLORS.card,
    // Neomorphic header shadow
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.card,
    justifyContent: 'center',
    alignItems: 'center',
    // Neomorphic button
    shadowColor: COLORS.dark,
    shadowOffset: { width: -2, height: -2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.dark,
    letterSpacing: 0.5,
  },
  progressContainer: {
    padding: 20,
    backgroundColor: COLORS.card,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    // Subtle inner shadow for depth
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  progressBar: {
    height: 8,
    backgroundColor: COLORS.border,
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
    // Neomorphic inset effect
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 1,
  },
  progressFill: {
    height: '100%',
    borderRadius: 12,
    // Gradient-like effect with primary color
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 2,
  },
  progressText: {
    fontSize: 14,
    color: COLORS.medium,
    textAlign: 'center',
    fontWeight: '600',
    // Responsive text size for longer text
    ...(screenWidth < 350 ? { fontSize: 12 } : {}),
  },
  formContainer: {
    flex: 1,
    padding: 20,
  },
  inputContainer: {
    marginBottom: 24,
  },
  label: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.dark,
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  input: {
    borderWidth: 0,
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    backgroundColor: COLORS.card,
    color: COLORS.dark,
    minHeight: 56,
    // Neomorphic input field
    shadowColor: COLORS.dark,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  selectInput: {
    borderWidth: 0,
    borderRadius: 16,
    padding: 16,
    backgroundColor: COLORS.card,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 56,
    // Neomorphic pressable effect
    shadowColor: COLORS.dark,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  selectInputText: {
    fontSize: 16,
    color: COLORS.dark,
    fontWeight: '600',
    flex: 1,
  },
  selectInputPlaceholder: {
    fontSize: 16,
    color: COLORS.light,
    flex: 1,
  },
  cameraButton: {
    borderWidth: 2,
    borderColor: COLORS.primary,
    borderRadius: 20,
    padding: 24,
    backgroundColor: COLORS.card,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 120,
    // Neomorphic camera button with accent
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  cameraButtonContent: {
    alignItems: 'center',
  },
  cameraButtonText: {
    fontSize: 16,
    color: COLORS.primary,
    marginTop: 12,
    textAlign: 'center',
    fontWeight: '600',
  },
  photoPreviewContainer: {
    alignItems: 'center',
    width: '100%',
  },
  photoPreview: {
    width: 80,
    height: 60,
    borderRadius: 12,
    marginRight: 8,
    // Neomorphic photo preview
    shadowColor: COLORS.dark,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  photoTakenText: {
    fontSize: 14,
    color: COLORS.success,
    fontWeight: '700',
    marginTop: 12,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: COLORS.card,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    // Subtle top shadow
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 16,
    flex: 1,
    marginHorizontal: 6,
    minHeight: 52,
    // Neomorphic button base
    shadowColor: COLORS.dark,
    shadowOffset: { width: 2, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  prevButton: {
    backgroundColor: COLORS.medium,
  },
  submitNowButton: {
    backgroundColor: COLORS.success,
    // Extra glow for submit button
    shadowColor: COLORS.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  nextButton: {
    backgroundColor: COLORS.primary,
    // Primary button glow
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  disabledButton: {
    backgroundColor: COLORS.light,
    // Reduced shadow for disabled state
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonText: {
    color: COLORS.card,
    fontSize: 14,
    fontWeight: '700',
    marginHorizontal: 4,
    letterSpacing: 0.5,
    // Responsive font size
    ...(screenWidth < 350 ? { fontSize: 12 } : {}),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(55, 58, 86, 0.6)', // Using COLORS.dark with opacity
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
    // Neomorphic modal
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.dark,
    letterSpacing: 0.5,
  },
  optionItem: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.card,
    // Subtle hover effect
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  optionText: {
    fontSize: 16,
    color: COLORS.dark,
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: COLORS.background,
  },
  loadingText: {
    fontSize: 16,
    color: COLORS.medium,
    marginTop: 16,
    textAlign: 'center',
    fontWeight: '600',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
    backgroundColor: COLORS.background,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.dark,
    marginTop: 20,
    marginBottom: 12,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 16,
    color: COLORS.medium,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 28,
  },
  backToHomeButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 16,
    // Neomorphic CTA button
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  backToHomeText: {
    color: COLORS.card,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  // Responsive adjustments for smaller screens
  '@media (max-width: 350)': {
    buttonContainer: {
      padding: 16,
    },
    button: {
      paddingVertical: 12,
      paddingHorizontal: 8,
      marginHorizontal: 4,
    },
    progressContainer: {
      padding: 16,
    },
    formContainer: {
      padding: 16,
    },
  },
});