import { StyleSheet } from 'react-native';
import COLORS from '../../utils/COLORS.js';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background || '#f5f5f5',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.primary || '#007AFF',
    paddingHorizontal: 20,
    paddingVertical: 15,
    paddingTop: 50,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  refreshButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 20,
    padding: 8,
    minWidth: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshButtonText: {
    fontSize: 16,
    color: '#ffffff',
  },
  mapContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  map: {
    width: '100%',
    height: '100%',
  },
  errorContainer: {
    backgroundColor: '#ffebee',
    borderLeftWidth: 4,
    borderLeftColor: '#f44336',
    padding: 16,
    margin: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  errorText: {
    fontSize: 16,
    color: '#c62828',
    textAlign: 'center',
    marginBottom: 12,
    fontWeight: '500',
  },
  retryButton: {
    backgroundColor: '#f44336',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  infoContainer: {
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    paddingHorizontal: 20,
    paddingVertical: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  infoText: {
    fontSize: 16,
    color: COLORS.medium || '#666666',
    textAlign: 'center',
    marginBottom: 8,
    fontWeight: '500',
  },
  coordinatesText: {
    fontSize: 12,
    color: COLORS.light || '#999999',
    textAlign: 'center',
    fontFamily: 'monospace',
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: COLORS.dark || '#333333',
    fontWeight: '500',
  },
  markerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.primary || '#007AFF',
    borderWidth: 3,
    borderColor: '#ffffff',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  controlsContainer: {
    position: 'absolute',
    bottom: 100,
    right: 16,
    flexDirection: 'column',
    alignItems: 'center',
  },
  controlButton: {
    backgroundColor: '#ffffff',
    borderRadius: 25,
    padding: 12,
    marginVertical: 4,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  controlButtonText: {
    fontSize: 18,
    color: COLORS.primary || '#007AFF',
  },
  mapTypeSelector: {
    position: 'absolute',
    top: 100,
    right: 16,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    overflow: 'hidden',
  },
  mapTypeButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  mapTypeButtonActive: {
    backgroundColor: COLORS.primary || '#007AFF',
  },
  mapTypeButtonText: {
    fontSize: 12,
    color: COLORS.dark || '#333333',
    fontWeight: '500',
  },
  mapTypeButtonTextActive: {
    color: '#ffffff',
  },
  // Fallback styles for Expo Go
  fallbackContainer: {
    backgroundColor: '#f0f8ff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    borderWidth: 2,
    borderColor: '#e3f2fd',
    borderStyle: 'dashed',
    borderRadius: 12,
  },
  fallbackTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.primary || '#007AFF',
    marginBottom: 16,
    textAlign: 'center',
  },
  fallbackText: {
    fontSize: 16,
    color: COLORS.medium || '#666666',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  locationInfo: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    minWidth: 200,
  },
  fallbackLocationTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary || '#007AFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  fallbackLocationText: {
    fontSize: 14,
    color: COLORS.dark || '#333333',
    textAlign: 'center',
    fontFamily: 'monospace',
    lineHeight: 20,
  },
  mapButton: {
    width: '100%',
    alignItems: 'center',
  },
  openMapText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary || '#007AFF',
    textAlign: 'center',
    marginTop: 12,
    padding: 8,
    backgroundColor: '#e3f2fd',
    borderRadius: 8,
  },
});