import { View, StyleSheet, Alert, Text, TouchableOpacity, Image } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    backgroundColor: "white",
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#f8f9fa',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    left: -90,
  },
  scrollContainer: {
    flex: 1,
  },
  uploadSection: {
    padding: 20,
    backgroundColor: "white",
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
  },
  documentName: {
    fontSize: 20,
    fontWeight: "600",
    color: "#6366F1",
    marginBottom: 12,
  },
  helpText: {
    fontSize: 14,
    color: "#666",
    lineHeight: 22,
    marginBottom: 20,
  },
  filePreviewContainer: {
    alignSelf: "center",
    marginVertical: 20,
    padding: 24,
    backgroundColor: "#EFF6FF",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  uploadArea: {
    height: 180,
    borderWidth: 2,
    borderColor: "#6366F1",
    borderRadius: 16,
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    backgroundColor: "#FAFAFA",
  },
  uploadText: {
    marginTop: 10,
    fontSize: 16,
    color: "#666",
    fontWeight: "500",
  },
  fileTypesContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 24,
  },
  fileType: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#F5F7FF",
    borderRadius: 8,
    marginHorizontal: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  fileTypeText: {
    fontSize: 14,
    color: "#6366F1",
    fontWeight: "500",
  },
  orText: {
    textAlign: "center",
    fontSize: 16,
    color: "#666",
    marginVertical: 16,
    fontWeight: "500",
  },
  cameraButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0F7FF",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  cameraButtonText: {
    fontSize: 16,
    color: "#3B82F6",
    marginLeft: 10,
    fontWeight: "500",
  },
  uploadDocumentButton: {
    backgroundColor: "#6366F1",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  uploadDocumentButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  recentDocumentsSection: {
    padding: 20,
    backgroundColor: "white",
  },
  recentDocumentsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 16,
    color: "#333",
  },
  documentItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    backgroundColor: "white",
    borderRadius: 8,
    marginBottom: 2,
  },
  documentIconContainer: {
    width: 45,
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
    backgroundColor: "#F0F7FF",
    borderRadius: 8,
  },
  documentInfo: {
    flex: 1,
  },
  documentTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 6,
    color: "#333",
  },
  documentDetails: {
    flexDirection: "row",
    alignItems: "center",
  },
  documentType: {
    fontSize: 12,
    color: "#666",
    marginRight: 10,
    fontWeight: "500",
  },
  documentSize: {
    fontSize: 12,
    color: "#666",
    marginRight: 10,
  },
  documentDate: {
    fontSize: 12,
    color: "#666",
  },
  documentStatus: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
    backgroundColor: "#F5F7FF",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  statusText: {
    fontSize: 12,
    color: "#6366F1",
    fontWeight: "500",
  },
  documentMenuButton: {
    padding: 8,
    backgroundColor: "#F5F7FF",
    borderRadius: 8,
  },
});