import { StyleSheet } from "react-native";
import COLORS from '../../utils/COLORS.js'; // Import your COLORS
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.card,
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: COLORS.background,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.dark,
    left: -90,
  },
  scrollContainer: {
    flex: 1,
  },
  uploadSection: {
    padding: 20,
    backgroundColor: COLORS.card,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  sectionIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  sectionTitleContainer: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.dark,
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: COLORS.medium,
    lineHeight: 20,
  },
  documentName: {
    fontSize: 20,
    fontWeight: "600",
    color: COLORS.primary,
    marginBottom: 12,
  },
  placeholderText: {
    fontSize: 18,
    fontWeight: "500",
    color: COLORS.medium,
    marginBottom: 12,
  },
  categorySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: COLORS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.primary,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  categorySelectorEmpty: {
    borderColor: COLORS.border,
    backgroundColor: COLORS.background,
  },
  expirationDateSelector: {
    borderColor: COLORS.accent2,
    borderStyle: 'dashed',
  },
  expirationDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  // Action Cards for Document Type and Date Selection
  actionCardsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    gap: 12,
  },
  actionCard: {
    flex: 1,
    backgroundColor: COLORS.background,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.border,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
    minHeight: 120,
  },
  actionCardSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.selected,
  },
  actionIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  actionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.dark,
    marginBottom: 4,
    textAlign: 'center',
  },
  actionDescription: {
    fontSize: 12,
    color: COLORS.medium,
    textAlign: 'center',
    lineHeight: 16,
  },
  actionDescriptionSelected: {
    color: COLORS.primary,
    fontWeight: '500',
  },
  // File Preview Section
  filePreviewSection: {
    marginBottom: 24,
  },
  filePreviewContent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.selected,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.success + '30',
  },
  fileIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.success + '20',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  fileDetails: {
    flex: 1,
  },
  fileName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.dark,
    marginBottom: 4,
  },
  fileStatus: {
    fontSize: 14,
    color: COLORS.success,
    fontWeight: '500',
  },
  removeFileButton: {
    padding: 4,
  },
  // Upload Methods
  uploadMethodsContainer: {
    marginBottom: 24,
  },
  uploadMethodsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.dark,
    marginBottom: 16,
  },
  uploadMethodCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  disabledUploadMethod: {
    backgroundColor: COLORS.background,
    opacity: 0.6,
  },
  uploadMethodIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  uploadMethodContent: {
    flex: 1,
  },
  uploadMethodTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.dark,
    marginBottom: 2,
  },
  uploadMethodSubtitle: {
    fontSize: 14,
    color: COLORS.medium,
  },
  // Upload Button
  uploadButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  disabledUploadButton: {
    backgroundColor: COLORS.light,
    shadowOpacity: 0,
    elevation: 0,
  },
  uploadButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  uploadButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.card,
  },
  // Help Container
  helpContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: COLORS.background,
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  helpText: {
    fontSize: 13,
    color: COLORS.medium,
    lineHeight: 18,
    flex: 1,
  },
  disabledText: {
    color: COLORS.light,
  },
  recentDocumentsSection: {
    padding: 20,
    backgroundColor: COLORS.card,
  },
  recentDocumentsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  recentDocumentsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.dark,
  },
  refreshButton: {
    padding: 8,
    backgroundColor: COLORS.selected,
    borderRadius: 8,
    minWidth: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorContainer: {
    backgroundColor: COLORS.danger + '10', // Light red background
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.danger + '30',
  },
  errorText: {
    fontSize: 14,
    color: COLORS.danger,
    marginBottom: 12,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: COLORS.danger,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignSelf: 'center',
  },
  retryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.card,
  },
  loader: {
    marginVertical: 20,
  },
  noDocumentsText: {
    fontSize: 16,
    color: COLORS.medium,
    textAlign: 'center',
    marginVertical: 20,
  },
  documentItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    backgroundColor: COLORS.card,
    borderRadius: 8,
    marginBottom: 2,
  },
  documentIconContainer: {
    width: 45,
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
    backgroundColor: COLORS.selected,
    borderRadius: 8,
  },
  documentInfo: {
    flex: 1,
  },
  documentTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 6,
    color: COLORS.dark,
  },
  documentDetails: {
    flexDirection: "row",
    alignItems: "center",
  },
  documentType: {
    fontSize: 12,
    color: COLORS.medium,
    marginRight: 10,
    fontWeight: "500",
  },
  documentSize: {
    fontSize: 12,
    color: COLORS.medium,
    marginRight: 10,
  },
  documentDate: {
    fontSize: 12,
    color: COLORS.medium,
  },
  documentStatus: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
    backgroundColor: COLORS.selected,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  statusText: {
    fontSize: 12,
    color: COLORS.primary,
    fontWeight: "500",
  },
  documentMenuButton: {
    padding: 8,
    backgroundColor: COLORS.selected,
    borderRadius: 8,
  },
  showMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: COLORS.selected,
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  showMoreText: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: '500',
    marginRight: 8,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    maxHeight: '80%',
    minHeight: '50%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.dark,
  },
  modalCloseButton: {
    padding: 8,
    backgroundColor: COLORS.background,
    borderRadius: 8,
  },
  modalScrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  categoryOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: COLORS.card,
    borderRadius: 12,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  selectedCategoryOption: {
    backgroundColor: COLORS.selected,
    borderColor: COLORS.primary,
  },
  categoryOptionText: {
    fontSize: 16,
    color: COLORS.dark,
    fontWeight: '500',
    flex: 1,
  },
  selectedCategoryOptionText: {
    color: COLORS.primary,
    fontWeight: '600',
  },
});